return {
	{ import = "plugins.colorschemes" },
	{ import = "plugins.extras.fun.drop" },
	{ import = "plugins.extras.optimizations.garbage-day" },
	{ import = "plugins.extras.editor.live-rename" },
	{ import = "plugins.extras.editor.highlight-undo" },
	{ import = "plugins.extras.editor.workspace-diagnostics" },
	{ import = "plugins.extras.editor.rainbow-delimiters" },
	{ import = "plugins.extras.editor.treesj" },
	{ import = "plugins.extras.coding.blink.colorful-menu" },
	{ import = "plugins.extras.style.popups.rounded" },
	{ import = "plugins.extras.ui.colorful-winsep" },
	{ import = "plugins.extras.ui.symbol-usage" },
	{ import = "plugins.extras.keys.snacks-picker.smart" },
	{ import = "plugins.extras.keys.lsp.hover-tab" },
	{ import = "plugins.extras.keys.lsp.workspace" },
	{ import = "plugins.extras.keys.bufferline.focus-left-or-right" },
	{ import = "plugins.extras.utils.langmapper" },
	{ import = "plugins.extras.utils.silicon" },
	{ import = "plugins.extras.utils.mason.disable" },
}
